#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  adduser --system --quiet --group --no-create-home sgctp || :
  chgrp sgctp /etc/sgctp/principals
  chmod 640 /etc/sgctp/principals
fi
# Automatically added by dh_installinit
if [ -x "/etc/init.d/sgctp-daemons" ]; then
	if [ ! -e "/etc/init/sgctp-daemons.conf" ]; then
		update-rc.d sgctp-daemons defaults >/dev/null
	fi
	invoke-rc.d sgctp-daemons start || exit $?
fi
# End automatically added section
